In [1]:
import numpy as np

## 1. Cálculo de entropía

In [2]:
# Función para calcular la entropía estimada a partir de las realizaciones
def entropy_estimation(data):
    unique_values, counts = np.unique(data, return_counts=True)
    probabilities = counts / len(data)  # Probabilidades estimadas (frecuencias relativas)
    entropy = -np.sum(probabilities * np.log2(probabilities))  # Cálculo de entropía
    return entropy

### 1.1 Ejemplo

In [3]:
# Realizaciones de las variables aleatorias X e Y
# (reemplazar estos valores con los datos reales de las realizaciones)
X = [1, 2, 1, 3, 2, 2, 3, 1, 1, 2]  # Ejemplo de realizaciones de X
Y = [2, 3, 2, 3, 1, 2, 3, 1, 3, 2]  # Ejemplo de realizaciones de Y
realizaciones = np.array([
    [1, 2],
    [2, 3],
    [1, 2],
    [3, 3],
    [2, 1],
    [2, 2],
    [3, 3],
    [1, 1],
    [1, 3],
    [2, 2]
])

# Calcular H(X) y H(Y) usando la función de estimación de entropía
H_X = entropy_estimation(X)
H_Y = entropy_estimation(Y)

# Mostrar los resultados
print(f"La entropía estimada H(X) es: {H_X:.4f} bits")
print(f"La entropía estimada H(Y) es: {H_Y:.4f} bits")

La entropía estimada H(X) es: 1.5219 bits
La entropía estimada H(Y) es: 1.5219 bits


## 2. Cálculo de entropía conjunta

In [4]:
import numpy as np

def calculo_entropia_conjunta(realizaciones):
    """
    Calcula el alfabeto de X e Y, las probabilidades conjuntas y las entropías de X y Y.
    
    Parámetros:
        realizaciones (array): Matriz de tamaño N x 2, donde cada columna contiene las realizaciones de una variable aleatoria.
    
    Retornos:
        alfabeto_x (array): Vector columna con los valores únicos de X, ordenado de menor a mayor.
        alfabeto_y (array): Vector columna con los valores únicos de Y, ordenado de menor a mayor.
        probabilidadConjunta (2D array): Matriz Mx x My con las probabilidades conjuntas de X e Y.
        entropiaX (float): Entropía de la variable X.
        entropiaY (float): Entropía de la variable Y.
        entropiaConjunta (float): Entropía conjunta de X y Y.
    """

    # --------------------------
    # 1️⃣ Extraer X e Y
    # --------------------------
    X = realizaciones[:, 0]
    Y = realizaciones[:, 1]

    # --------------------------
    # 2️⃣ Obtener los alfabetos (valores únicos ordenados)
    # --------------------------
    alfabeto_x = np.unique(X)
    alfabeto_y = np.unique(Y)

    Mx = len(alfabeto_x)
    My = len(alfabeto_y)

    # --------------------------
    # 3️⃣ Inicializar la matriz de frecuencias conjuntas
    # --------------------------
    frecuencia_conjunta = np.zeros((Mx, My))

    # --------------------------
    # 4️⃣ Contar ocurrencias de cada par (x, y)
    # --------------------------
    for i, x in enumerate(alfabeto_x):
        for j, y in enumerate(alfabeto_y):
            frecuencia_conjunta[i, j] = np.sum((X == x) & (Y == y)) 

    # --------------------------
    # 5️⃣ Calcular la matriz de probabilidades conjuntas
    # --------------------------
    probabilidadConjunta = frecuencia_conjunta / len(X)

    # --------------------------
    # 6️⃣ Calcular las distribuciones marginales
    # --------------------------
    p_x = np.sum(probabilidadConjunta, axis=1)  # Suma sobre Y
    p_y = np.sum(probabilidadConjunta, axis=0)  # Suma sobre X

    # --------------------------
    # 7️⃣ Calcular las entropías
    # --------------------------
    eps = 1e-12  # Pequeño valor para evitar log(0)
    entropiaX = -np.sum(p_x * np.log2(p_x + eps))
    entropiaY = -np.sum(p_y * np.log2(p_y + eps))
    entropiaConjunta = -np.sum(probabilidadConjunta * np.log2(probabilidadConjunta + eps))

    # --------------------------
    # 8️⃣ Retornar resultados
    # --------------------------
    return alfabeto_x, alfabeto_y, probabilidadConjunta, entropiaX, entropiaY, entropiaConjunta

alfabeto_x, alfabeto_y, Pxy, HX, HY, HXY = calculo_entropia_conjunta(realizaciones)

print("Alfabeto X:", alfabeto_x)
print("Alfabeto Y:", alfabeto_y)
print("\nProbabilidad conjunta P(X,Y):\n", Pxy)
print(f"\nH(X) = {HX:.4f} bits")
print(f"H(Y) = {HY:.4f} bits")
print(f"H(X,Y) = {HXY:.4f} bits")


Alfabeto X: [1 2 3]
Alfabeto Y: [1 2 3]

Probabilidad conjunta P(X,Y):
 [[0.1 0.2 0.1]
 [0.1 0.2 0.1]
 [0.  0.  0.2]]

H(X) = 1.5219 bits
H(Y) = 1.5219 bits
H(X,Y) = 2.7219 bits


## 3. Cálculo de entropía condicional

In [8]:
import numpy as np

def calculo_entropia_condicional(realizaciones):
    """
    Calcula el alfabeto de X e Y, las probabilidades condicionales y las entropías condicionales de X|Y y Y|X.
    
    Parámetros:
        realizaciones (array): Matriz de tamaño N x 2, donde cada columna contiene las realizaciones de una variable aleatoria.
    
    Retornos:
        alfabeto_x (array): Valores únicos de X, ordenados.
        alfabeto_y (array): Valores únicos de Y, ordenados.
        probabilidad_X_dado_Y (2D array): Matriz Mx x My con P(X|Y).
        probabilidad_Y_dado_X (2D array): Matriz Mx x My con P(Y|X).
        entropia_X_dado_Y (float): Entropía condicional H(X|Y).
        entropia_Y_dado_X (float): Entropía condicional H(Y|X).
    """

    # 1️⃣ Extraer las realizaciones de X e Y
    X = realizaciones[:, 0]
    Y = realizaciones[:, 1]
    N = len(X)

    # 2️⃣ Obtener el alfabeto (valores únicos) de X e Y
    alfabeto_x = np.unique(X)
    alfabeto_y = np.unique(Y)

    Mx = len(alfabeto_x)
    My = len(alfabeto_y)

    # 3️⃣ Crear la matriz de frecuencias conjuntas
    frecuencia_conjunta = np.zeros((Mx, My))

    # 4️⃣ Calcular las frecuencias conjuntas recorriendo las realizaciones
    for i, x in enumerate(alfabeto_x):
        for j, y in enumerate(alfabeto_y):
            frecuencia_conjunta = np.sum((X == x) & (Y == y))

    # 5️⃣ Convertir a probabilidades conjuntas
    p_xy = frecuencia_conjunta / N

    # 6️⃣ Calcular las marginales
    p_x = np.sum(p_xy, axis=1)  # Suma sobre columnas → p(x)
    p_y = np.sum(p_xy, axis=0)  # Suma sobre filas → p(y)

    # 7️⃣ Calcular las probabilidades condicionales
    eps = 1e-12  # para evitar divisiones por cero
    probabilidad_X_dado_Y = p_xy / (p_y + eps)    # divide cada columna por p(y)
    probabilidad_Y_dado_X = (p_xy.T / (p_x + eps)).T  # divide cada fila por p(x)

    # 8️⃣ Calcular las entropías condicionales
    # H(X|Y) = Σ_y p(y) * H(X|Y=y)
    # H(Y|X) = Σ_x p(x) * H(Y|X=x)

    H_X_dado_Y = 0
    for j in range(My):
        H_X_dado_Y -= p_y[j] * np.sum(probabilidad_X_dado_Y[:, j] * np.log2(probabilidad_X_dado_Y[:, j] + eps))

    H_Y_dado_X = 0
    for i in range(Mx):
        H_Y_dado_X -= p_x[i] * np.sum(probabilidad_Y_dado_X[i, :] * np.log2(probabilidad_Y_dado_X[i, :] + eps))

    # 9️⃣ Retornar resultados
    return alfabeto_x, alfabeto_y, probabilidad_X_dado_Y, probabilidad_Y_dado_X, H_X_dado_Y, H_Y_dado_X


### 3.1 Ejemplo 

In [6]:
_, _, prob_XY, prob_YX, entr_XY, entr_YX = calculo_entropia_conjunta(realizaciones)
print(entr_XY)
print(entr_YX)

1.5219280948830343
2.7219280948772635


## 4. Cálculo información mutua

In [9]:
def calculo_informacion_mutua(realizaciones):
    """
    Calcula la información mutua entre dos variables aleatorias discretas.
    
    Parámetros:
        realizaciones (array): Matriz N x 2 con las realizaciones de dos variables aleatorias discretas.
    
    Retorno:
        informacionMutua (float): Escalar que representa la información mutua entre las dos variables.
    """
    _, _, _, entropiaX, entropiaY, entropiaConjunta = calculo_entropia_conjunta(realizaciones)
    informacionMutua = entropiaX + entropiaY - entropiaConjunta
    return informacionMutua

### 4.1 Ejemplo

In [10]:
# Ejemplo de uso con una matriz de realizaciones

# Calcular la información mutua
informacionMutua = calculo_informacion_mutua(realizaciones)
print(informacionMutua)

0.321928094888805


## 5. Capacidad canal 

In [15]:
def capacidad_canal_44(P):
    """
    Calcula la capacidad de un canal de 4x4 y la distribución de entrada óptima.
    """
    capacidad_canal = 0
    pX_optima = np.zeros(4)
    paso = 0.05
    
    # Pre-calcular la entropía de cada fila H(Y|X=xi)
    H_filas = np.zeros(4)
    for i in range(4):
        fila = P[i, :]
        p_pos = fila[fila > 0]
        H_filas[i] = -np.sum(p_pos * np.log2(p_pos))

    # Bucle de optimización por fuerza bruta
    for p1 in np.arange(0, 1 + paso, paso):
        for p2 in np.arange(0, 1 - p1 + paso, paso):
            for p3 in np.arange(0, 1 - p1 - p2 + paso, paso):
                p4 = 1 - p1 - p2 - p3
                
                if p4 < -1e-9: continue
                p4 = max(0, p4)

                pX = np.array([p1, p2, p3, p4])

                # 1. Calcular salida p(Y)
                pY = np.dot(pX, P)

                # 2. Calcular H(Y) evitando log(0)
                pY_pos = pY[pY > 1e-12]
                HY = -np.sum(pY_pos * np.log2(pY_pos))

                # 3. Calcular H(Y|X)
                HYX = np.dot(pX, H_filas)

                # 4. Información Mutua
                informacion_mutua = HY - HYX

                # 5. Guardar el máximo
                if informacion_mutua > capacidad_canal:
                    capacidad_canal = informacion_mutua
                    pX_optima = pX.copy()

    return capacidad_canal, pX_optima

# --- EJEMPLO DE USO REAL ---
# Definimos una matriz donde cada fila sume 1. 
# Este es un canal donde el símbolo se recibe bien el 70% de las veces.
P = np.array([
    [0.7, 0.1, 0.1, 0.1],
    [0.1, 0.7, 0.1, 0.1],
    [0.1, 0.1, 0.7, 0.1],
    [0.1, 0.1, 0.1, 0.7]
])

# Calcular la capacidad del canal y el vector de entrada óptimo
capacidad, pX_opt = capacidad_canal_44(P)

print(f"Capacidad del canal: {capacidad:.4f} bits/símbolo")
print(f"Distribución óptima p(X): {pX_opt}")

Capacidad del canal: 0.6432 bits/símbolo
Distribución óptima p(X): [0.25 0.25 0.25 0.25]


In [12]:
# Ejemplo de uso con una matriz de canal 4x4
P = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])

# Calcular la capacidad del canal y el vector de entrada óptimo
capacidad_canal, pX_optima = capacidad_canal_44(P)
capacidad_canal, pX_optima

(0, array([0., 0., 0., 0.]))